version: '3.8'
services:
  server:
    image: 'nginx:1.22-alpine'
    depends_on:
      - backend
      - frontend
    volumes:
      - './templates/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './ssl:/ssl:ro'
    ports:
      - '8000:443'
  postgresql:
    image: postgres:10
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: DemoPa$$$$
      POSTGRES_DB: demodb
    volumes:
      - db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    depends_on:
      mysqldb:
       condition: service_healthy
    build: ./backend
    restart: unless-stopped
    ports:
      - 8080
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=MeetDB
      - DB_PORT=3306
      - NODE_DOCKER_PORT=8080
      - >-
        TOKEN_KEY=8ff491fd046ddb6646dccc64b9b17efd76cb4a7f62afd5a8ccfe1da11e65bacd
    stdin_open: true
    tty: true
  frontend:
    depends_on:
      - backend
    build: ./frontend
    restart: unless-stopped
    ports:
      - 3000
volumes:
  mysqldb: null
