version: "3.8"
services:
    mysqldb:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=MeetDB
        ports:
            - 3306
        volumes:
            - mysqldb:/var/lib/mysql
    backend:
        depends_on:
            - mysqldb
        build: ./backend
        restart: unless-stopped
        ports:
            - 8080:8080
        environment:
            - DB_HOST=mysqldb
            - DB_USER=root
            - DB_PASSWORD=password
            - DB_NAME=MeetDB
            - DB_PORT=3306
            - NODE_DOCKER_PORT=8080
            - TOKEN_KEY=8ff491fd046ddb6646dccc64b9b17efd76cb4a7f62afd5a8ccfe1da11e65bacd
        stdin_open: true
        tty: true
    frontend:
        depends_on:
            - backend
        build: ./frontend
        restart: unless-stopped
        environment:
            REACT_APP_API_LINK: http://192.168.0.21:8080
        ports:
            - 3000:3000
volumes:
    mysqldb:
