version: "3.8"
services:
    mysqldb:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=$MYSQLDB_DATABASE
        ports:
            - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
        volumes:
            - db:/var/lib/mysql
    backend:
        depends_on:
            - mysqldb
        build: ./backend
        restart: unless-stopped
        ports:
            - 6868:8080
        environment:
            - DB_HOST=mysqldb
            - DB_USER=root
            - DB_PASSWORD=password
            - DB_NAME=MeetDB
            - DB_PORT=3306
        stdin_open: true
        tty: true
    frontend:
        depends_on:
            - backend
        build: ./frontend
        restart: unless-stopped
        environment:
          REACT_APP_API_LINK: http://localhost:6868
        ports:
            - 3000:3000
volumes:
    db:
