version: '1'
services:
  db:
    image: mysql/mysql-server
    volumes:
       - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: MeetDatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports: 
    - 8080:80
  server:
    image:
     